test_that("diagnostics and plotting", {
  skip_if(skip_ADMB)
  fit <- readRDS('fit_admb.RDS')
  sp <- extract_sampler_params(fit)
  expect_is(sp,  'data.frame')
  plot_sampler_params(fit, TRUE)
  pairs(fit)
  pairs(fit, pars=1:3, order='slow')
  pairs(fit, pars=1:3, order='fast')
  pairs(fit, pars=c('a', 'lp__', 'b'), add.monitor=FALSE)
  expect_warning(pairs(fit, pars=c('a', 'b', 'c')), 'Some par names did not match')
  expect_error(pairs(fit, pars=c('a')), 'only makes sense for >=2')
  pairs(fit, add.mle=FALSE)
  pairs(fit, add.mle=FALSE, diag='hist')
  pairs(fit, add.mle=FALSE, diag='acf')
  expect_error(pairs(fit, add.mle=FALSE, diag='bad'), 'should be one of')
  plot_marginals(fit)
  plot_marginals(fit, add.monitor=FALSE)
  plot_marginals(fit, add.mle=FALSE)
  x <- plot_uncertainties(fit, plot=FALSE)
})
