on: [push, pull_request]

name: calc-coverage

jobs:
  calc-coverage:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v1

      - uses: r-lib/actions/setup-pandoc@v1

      - name: Get admb and put in path
        run: |
          wget https://github.com/admb-project/admb/releases/download/admb-12.2/admb-12.2-linux.zip
          sudo unzip admb-12.2-linux.zip -d /usr/local/bin
          sudo chmod 755 /usr/local/bin/admb-12.2/bin/admb
          rm admb-12.2-linux.zip
          echo "/usr/local/bin/admb-12.2/bin" >> $GITHUB_PATH

      - name: Query dependencies
        run: |
          install.packages('remotes')
          saveRDS(remotes::dev_package_deps(dependencies = TRUE), ".github/depends.Rds", version = 2)
          writeLines(sprintf("R-%i.%i", getRversion()$major, getRversion()$minor), ".github/R-version")
        shell: Rscript {0}

      - name: Cache R packages
        uses: actions/cache@v2
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-${{ hashFiles('.github/depends.Rds') }}
          restore-keys: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-

      - name: Install dependencies
        run: |
          install.packages(c("remotes"))
          remotes::install_deps(dependencies = TRUE)
          remotes::install_cran("covr")
        shell: Rscript {0}

      - name: Test coverage
        run: covr::codecov()
        shell: Rscript {0}
